### ISSUE TITLE
Duplicate messages in chat events

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#31]
1. Sometimes apps are getting duplicate events so duplicated messages in chat window. It's not happening every time. Please check attached video:

https://user-images.githubusercontent.com/41280808/114341705-bb54ce00-9b9d-11eb-8cb1-a69d5373d759.mp4

**Comment by ALobastov** [comment]
1. Please provide xCode log showing complete traffic between server and the app.

2. In order to allow getting case history or closing the case, the scenario which handles chat session must specify a case first. When scenario specifies the case, the application receives chatSessionCaseSet event which indicates that the app may now work with the case (get history or close it). The error you see means that scenario did not set a case. Again, the full log is needed to see exactly what is happening. The log should cover entire session from the requestChat() and until the end.

3. Please open separate GitHub issue for each problem. This way we can effectively work on them. Do not report multiple problems in one issue.

**Comment by ALobastov** [comment]
Still need xCode log; such issues are impossible to investigate without the log. Need to see exact requests the application sends and exact responses it receives from the server.

**Comment by NancyKashyap-Stride** [comment]
Please find attached logs and screenshots.

![IMG_0259](https://user-images.githubusercontent.com/41280808/114485621-95880180-9c4f-11eb-9883-e91203f12e8f.PNG)
![IMG_0258](https://user-images.githubusercontent.com/41280808/114485627-97ea5b80-9c4f-11eb-83e6-b63493e50bb3.PNG)
![IMG_0257](https://user-images.githubusercontent.com/41280808/114485628-991b8880-9c4f-11eb-816b-cd01d85a1233.PNG)

**Comment by NancyKashyap-Stride** [comment]
I am not sure if this is relevant with this bugs but I have noticed this happens when agent send 4-5 messages at once. If there is some interval in sending messages from agent then duplicate messages are not received by apps.

**Comment by ALobastov** [comment]
Thank you for the log. Per log, the application performs the following:

2021-04-13 11:49:02.187584+1000:
1. Application creates a new chat session; chat_id: 71bf1063-2ff8-4737-9b71-04a0f57f3293
2. Once session is created, the library starts polling for new events automatically. Since there are events available on the server already they are received and rendered by the application
3. In the meantime, application calls getChatHistory() method which returns a full history of the events for the session, including the ones already received on step 2 above. Application renders them second time - here is where we see duplicate events.
4. Application also immediately calls getCaseHistory() method. This is wrong as scenario have not set the case yet. Application should wait for the chatSessionCaseSet event before it can call getCaseHistory() or closeCase() requests. As result, the getCaseHistory() request fails with error 406/5601 - "No case is specified for this session." This is not harmful and not related to duplicate messages though; just a side note. 

2021-04-13 11:51:38.063027+1000: the application performs requestChat() again (while the existing chat session is still in progress) - there was no chatSessionEnded event received by the ap. The server does not allow more than one chat session per application, so this second requestChat() returns the same chat_id and "is_new_chat" = false. Application seem to ignore this and calls getChatHistory() again which returns a full history of the session, including the messages already received and rendered by the app. This history is rendered by the app again - hence the duplicate messages.

It looks like the application issue. Application should:
1. Assume that there only one chat session (one chatId) could exist at the moment
2. Should not call requestChat() again if the session is already in progress
3. If application logic still requires to call requestChat() again (not sure why it would need it but anyway) - the application must check the result for the matching chatId and for the ContactCenterChatSessionProperties.isNewChat attribute - it indicates if it is a new session or existing session
4. Most important. Each message (chatSessionMessage event) within a session has the messageID attribute. This attribute uniquely identifies a message within a session. If application uses the getChatHistory() API method this will lead to receiving the same chatSessionMessage event twice - one as result of automatic event polling via ContactCenterEventsDelegating delegate; another is as the response to the getChatHistory() request. It is the application responsibility to check the messageID for all received messages and avoid rendering the same message (message with the same messageID) more than once.

**Comment by ALobastov** [comment]
Since there is no response we assume the issue can be closed now.
