### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#34]
Please find attached logs to subscribe for firebase push notifications. iOS app is not receiving any notifications when app is not running or app is in background. 
I suppose fcm api token is already setup.

[push_notifications.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6300902/push_notifications.zip)

**Comment by ALobastov** [comment]
In order to receive push notifications via Firebase, the application should be configured in the Firebase Console, then the Firebase Server Key should be added to the messaging entry configuration in Portal. Please communicate this to the person who is responsible for the server configuration. BrightPattern development does not have an access to the server configuration.
