### ISSUE TITLE
Push notifications payload data 

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#36]
Push notifications in device system notification center title is showing as keyChatNewMessageTitle, keyChatInactivityTimeoutTitle. Notifications payload data should contain relevant title. Please find attached logs.

[Push_Notifications_Payload.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6314963/Push_Notifications_Payload.zip)

**Comment by ALobastov** [comment]
The title and subtitle of the push notifications are localizable strings. The server uses the client side localization approach per https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

The mobile application must use Localizable.strings to specify the strings for each supported language. Server uses the following string keys for iOS notification:

- **title-loc-key**: the key of the title string. It does not have any arguments. Typical value is "You have a new message"
- **subtitle-loc-key**: the key of the subtitle string. It may have one argument - name of the message sender. Typical value "From %@"
- **subtitle-loc-args**: subtitle arguments, like name of the sender. Will be substituted instead of %@ in the subtitle. I.e. if subtitle-loc-args is ["John Doe"] and subtitle-loc-key string is "From %@" the notification will show "From John Doe"
